config/routes.rb
Rails.application.routes.draw do
#  get 'availability_list', to: 'availability_list#index'
  devise_for :users
  resources :users
  resources :friendships
  resources :availability
  root to: "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :user

  validates_uniqueness_of :available_hour, scope: [:available_on, :user_id]
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"

  validates_uniqueness_of :user_id, scope: :friend_id#, message: "You already befriended this user"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :friendships
  has_many :friends, through: :friendships
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id"
  has_many :inverse_friends, through: :inverse_friendships, source: :user
  has_many :availability
  validates_presence_of :name, :email, :phone

  #https://stackoverflow.com/questions/26452245/how-can-i-display-all-users-except-current-user-and-current-users-friends-in-ru
  scope :all_except, -> (user){ where.not(id: user) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/availability_controller.rb
class AvailabilityController < ApplicationController
  def create
    @availability = current_user.availability.build(available_on: Date.today, available_hour: params[:available_hour])
    respond_to do |format|
      if @availability.save
        format.json {render json: @availability}
        format.html {
          flash[:notice] = "New availability added!"
          redirect_to current_user
        }
      else
        format.json {render json: @availability.errors, status: :unprocessable_entity}
        format.html {
          flash[:error] = "Error adding availability"
          redirect_to current_user
        }
      end
    end
  end

  def destroy
    #no availabilityid. However, can we find the availability based on: current_user, date, and available_hour?
    @availability = current_user.availability.find(params[:id])
    respond_to do |format|
      if @availability.destroy
        format.json {render head :no_content}
        format.html {
          flash[:notice] = "Availability removed"
          redirect_to current_user
        }
      end
    end
  end
end

app/controllers/availability_list_controller.rb
# frozen_string_literal: true

class AvailabilityListController < ApplicationController
  layout "availability_list"

  def index
    @availability_list_props = { name: "Stranger" }
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    @friendship = current_user.friendships.build(friend_id: params[:friend_id])
    if @friendship.save
      flash[:notice] = "New friend added!"
      redirect_to current_user
    else
      flash[:error] = "Error adding friend"
      redirect_to current_user
    end
  end

  def destroy

    @friendship = current_user.friendships.where(user_id: params[:user_id], friend_id: params[:friend_id])
    @friendship[0].destroy
    flash[:notice] = "Remove friendship"
    redirect_to current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all_except(current_user).order(:name)
  end

  def show
    @user = current_user
    @users = User.all_except(current_user).order(:name)
    @friends = current_user.friends.order(:name)
    @availabilities = @user.availability.group_by(&:available_on)

    respond_to do |format|
      format.html {}
      format.json {
        render json: @availabilities
      }
    end
  end

  def create_availability
    @user = current_user
    @availability = current_user.availability.new
    if @availability.save
      redirect_to root_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  @green = "#36D7B7"
  @gray = "#B7BABB"
  @red = "#EC644B"

  def show_available_hour(model)
    return model.availability.group_by(&:available_on)
  end

  def say_hello
    return "hello"
  end

  def show_availability_id(user, hour)
    return Availability.where(user_id: user.id, available_hour: hour, available_on: Date.today)[0]
  end

  def availability_hours_object(arr)
    obj = {}
    24.times {|el| obj[el] = "null"}
    arr.each {|el| obj[el] = true}

    return obj
  end

  def get_user_availability_object(user)
    return availability_hours_object(user.availability.where(available_on: Date.today).map{|el| el.available_hour})
    #returns {0 => null, 1 => true, 2=> null, ... 23}
  end

  def get_user_availability_array(user)
    return user.availability.where(available_on: Date.today).map{|el| el.available_hour}
    #if user is available at 1, 3, and 4, then returns [1,3,4]
  end

  def which_color(availability_bool)
    case availability_bool
    when true
      return "green"
    when false
      return "red"
    else
      return "grey"
    end
  end

end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/availability_list/index.html.erb
<h1>Hello Availability</h1>
<%= react_component("AvailabilityList", props: @availability_list_props, prerender: false) %>

app/views/friendships/create.html.erb
<h1>Friendships#create</h1>
<p>Find me in app/views/friendships/create.html.erb</p>

app/views/friendships/destroy.html.erb
<h1>Friendships#destroy</h1>
<p>Find me in app/views/friendships/destroy.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_nav.html.erb
<!--<nav class="navbar">
  <ul class="nav navbar-nav">
   <% if user_signed_in? %>
      <li class="nav-item">
        <a class="nav-link"><%= link_to current_user.name, user_path(current_user) %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link"><%= link_to "Log Out", destroy_user_session_path, method: :delete %></a>
      </li>
    <% else %>
      <li class="nav-item">
        <a class="nav-link">
          <%= link_to "Log In", new_user_session_path %>
        </a>
      </li>
    <% end %>
  </ul>
</nav>
-->

<div class="nav">
  <% if user_signed_in? %>
    <%= link_to image_tag(current_user.photo, class: "nav-profile-photo"), user_path(current_user), class: "header-text" %>
    <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "header-text" %>
  <% else %>
    <%= link_to "Log In", new_user_session_path %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameNiteScheduler</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  </head>

  <body>
    <%= render "layouts/nav" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>

</html>

app/views/layouts/availability_list.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsWithWebpacker</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'availability-list-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsWithWebpacker</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'hello-world-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<div class="three"></div>
<h1>Users</h1>
<ul>
  <% @users.each do |user| %>
  <li><%= user.name %> (<%= link_to "add user", friendships_path(friend_id: user), method: :post %>)</li>
  <% end %>
</ul>

app/views/users/show.html.erb
<div class="main-container">
  <div class="search-bar-container">
    <input type="text" id="myInput" onkeyup="searchFriend()" placeholder="Enter your friend name...">
  </div>

  <div class="schedule-photo-container">
    <div class="user-photos-container">

      <!-- current_user photo -->
      <div>
        <div class="photo-container">
          <img id=<%= @user.name %> class="user-photo" src=<%= @user.photo %> />
          <div><span><%= @user.name %></div>
        </div>
      </div>

      <!-- userPhotos for searching -->
      <div id="userPhotos">

        <!-- current_user friends -->
        <% @friends.map do |user| %>
          <div id=<%= user.name %> class="photo-container friends-photo-container">
            <img class="user-photo" src=<%= user.photo %> />
            <div class="photo-names">
              <span><%= user.name %></span>
              <span><%= link_to "Remove", friendship_path(user_id: @user.id, friend_id: user.id), method: :delete, class: 'small-text' %></span>
            </div>
          </div>
        <% end %>
      </div>

    </div>

    <div class="schedule-container">

      <!-- get hours displayed horizontally on top -->
      <% (0..23).to_a.map do |el| %>
        <div class="each-hour"><span><%= el.to_s + ":00" %></span></div>
      <% end %>
      <!-- end hours display -->

      <!-- current_user availability -->
      <div class="user-hours">
        <div id=<%= @user.name%> class="hours-row">
          <% get_user_availability_object(@user).keys.map do |el| %>
            <button data-availability-id=<%= show_availability_id(current_user, 1).id %> data-user-id=<%= @user.id %> data-hour=<%= el %> class=<%=which_color(get_user_availability_object(@user)[el])%> %><%=  %></button>
          <% end %>
        </div>

        <!-- end current_user availability -->
        <div id="userHours">
          <% @friends.each do |friend| %>
            <div id=<%= friend.name %> class="hours-row">
              <% get_user_availability_object(friend).keys.map do |el|  %>
                <button data-hour=<%= el %> data-user-id=<%= friend.id %> class=<%= which_color(get_user_availability_object(friend)[el]) %> ><%= el%></button>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>




<ul class="custom-menu">
  <li>Remove Friend</li>
</ul>



<h3>Friends:</h3>
<ul>
  <% @user.friendships.each do |friendship| %>
    <li>
      <%= friendship.friend.name %> - <%= link_to "Remove friend", friendship, method: :delete %>
      <ul>
        <% show_available_hour(friendship.friend).keys.each do |available_date, index| %>
          <li>
            <%= available_date %>
            <ul>
              <% show_available_hour(friendship.friend)[available_date].each do |d| %>
                <li><%= d.available_hour %></li>
              <% end %>
            </ul>
          </li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ul>


<h2>Availability </h2>
<!--
<h1><%= get_user_availability_object(current_user) %></h1>
<h1><%= get_user_availability_array(current_user) %></h1>
-->
<form method="post" action="/availability">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <select name="available_hour" class="custom-select">
    <% (0..23).to_a.each do |el| %>
      <option value=<%= el %>><%= el%></option>
    <% end %>
  </select>
  <button type="submit" class="btn btn-primary">Add Availability</button>
</form>



<form method="post" action="/availability">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <button name="available_hour" value=0 type="submit" class="nowhere-block">Add Availability</button>
</form>




<hr />

<ul>
  <% @availabilities.keys.each do |available_date, index| %>
    <li>
      <%= available_date %>:
      <ul>
        <% @availabilities[available_date].each do |d| %>
          <li><%= d.available_hour %> - <%= link_to "Remove hour", availability_path(d), method: :delete %></li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ul>

<h2>Friended by:</h2>
<ul>
  <% @user.inverse_friends.each do |user| %>
    <li><%= user.name %></lik>
  <% end %>
</ul>
<p><%= link_to "Back to users list", users_path %></p>


<h2>Users</h2>

<ul>
  <% @users.each do |user| %>
  <li><%= user.name %> (<%= link_to "add user", friendships_path(friend_id: user), method: :post %>)</li>
  <% end %>
</ul>